### ISSUE TITLE
[Feature Request] Is it possible to have a thermostat per zone?

### ISSUE THREAD

**Issue by Tech-BH2** [uswong/homebridge-myplace#1]
**Is your feature request related to a problem? Please describe:**

No problem as such, just would be nice to have thermostats for each temperature controlled zone.

**Describe the solution you'd like:**

While the current plugin is great and you can individually set temperature for each ‘myzone’ by  first hitting the rotation of each zone fan, it would be more intuitive to have a thermostat per ‘myzone’ for the 1 air conditioner with the fan speed controlling each damper. I understand that you couldn’t have one on heat and another on cool, but it would be more intuitive for those with temperature sensors for each zone.

**Describe alternatives you've considered:**

N/A

**Additional context:**

**Advantage Air System:**

* **Control Unit:** MyPlace
* **Temperature Sensors**: **Yes** 

Thank you

**Comment by uswong** [comment]
Thanks for suggesting that @Tech-BH2! 

It is certainly a good idea to be able to change the temperature setting for each zone with temperature sensor which I have considered doing it before but did not go down that path due to the exact challenge you mentioned.  

In any case, I will have another crack when I have time to get around to it.

**Comment by uswong** [comment]
Completed with release v2.1.0.

**Comment by Tech-BH2** [comment]
Thank you! Will test it shortly!

**Comment by uswong** [comment]
Just released an incremental release v2.1.1 as I overlooked one minor thing.  Test it out and please report here if there is any issue.

Cheers.

**Comment by Tech-BH2** [comment]
Working well for me so far, will let you know if i have any issues.
This is awesome thank you :)

**Comment by Tech-BH2** [comment]
Ok so I’ve played around with the new version and it does work really well the only thing is now I’ve lost the ability see the current temperature of each room in each room via HomeKit. There doesn’t seem to be an additional TemperatureSensor for each thermostat? I did like that ability previously as you could use it for automating starting the air conditioning

**Comment by Tech-BH2** [comment]
I’ve also looked at the code and your work is amazing. You made all those additional lines and functions so quickly!

**Comment by Tech-BH2** [comment]
I just realised my issue.
The current temperature for the thermostats are limited to a minimum of 16*c, in my locality it gets much lower. Manually updated it to 0 and i can see the current temperatures of each zone.
Thank you

**Comment by uswong** [comment]
Very good feedback on the minimum temperature.  It can be easily done!  What do you think is the realistic low? -20 degrees Celsius? By the way, just curious, where are you located?

**Comment by uswong** [comment]
I have decided to open up the current temperature to the default range of -270 to 100.  I am keeping the target temperature as 16-32.  That is the target temperature range on all AdvantageAir tablets. I have now released an incremental release v2.1.2.  

Hopefully this will work well for you.

Cheers.

**Comment by Tech-BH2** [comment]
Perfect!

yeah makes sense to allow the current temperature as the default, while the ranges for target temperature limited :-)

Kiwi here 👍 

thanks for this feature.
Works brilliantly

**Comment by MRW-NZ** [comment]
> Perfect!
> 
> yeah makes sense to allow the current temperature as the default, while the ranges for target temperature limited :-)
> 
> Kiwi here 👍
> 
> thanks for this feature. Works brilliantly

This was a great suggestion and thanks to uswong for implementing it - I literally just came here to suggest the same thing
